spring:
  application:
    name: ntconsult
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      input-bindings: calcular-voto
      output-bindings: calcular-voto

topic:
  calcular-votos-pauta: calcular-votos-pauta

camel:
  component:
    quartz2:
      cron:
        v1: cron:tab?schedule=0/60+*+*+*+*+?

url:
  cpf: https://api.invertexto.com/v1/validator
  token: 16204|OedYicokYDVgT2EgopqN11crVPjpmxVJ
  type: cpf