spring:
  application:
    name: ntconsult
  datasource:
    url: jdbc:postgresql://ntconsult.c7mo8qw6iksg.us-east-2.rds.amazonaws.com:5432/ntconsult
    username: postgres
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: a77c498fe7a674c838403316b489029f-1648633060.us-east-2.elb.amazonaws.com
    port: 5672
    username: admin
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

topic:
  calcular-votos-pauta: calcular-votos-pauta

camel:
  component:
    quartz2:
      cron:
        v1: cron:tab?schedule=0/60+*+*+*+*+?

url:
  cpf: https://api.invertexto.com/v1/validator
  token: 16204|OedYicokYDVgT2EgopqN11crVPjpmxVJ
  type: cpf